# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

# Environment variables required:
# - PYPI_USER / PYPI_PASS: for publishing package to PyPi

version: 2


references:

  container_python27: &container_python27
    docker:
      - image: circleci/python:2.7.13
    working_dir: ~/project

  container_python36: &container_python36
    docker:
      - image: circleci/python:3.6.2

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v0-repo-{{ .Branch }}-{{ .Revision }}
        - v0-repo-{{ .Branch }}
        - v0-repo

  save_repo: &save_repo
    save_cache:
      key: v0-repo-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/project     

jobs:

  build_and_test_27:
    <<: *container_python27
    steps:  
      - *restore_repo
      - checkout
      - *save_repo
      - restore_cache:
          keys: 
            - v0-dependencies27-{{ checksum "requirements.txt"}}
            - v0-dependencies27        
      - run: |
            pip install virtualenv
            virtualenv ~/venv27
            . ~/venv27/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install .
            cd test
            pytest -v --cov satstac --cov-report term-missing
      - save_cache:
          key: v0-dependencies27-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv27

  build_and_test_36:
    <<: *container_python36
    steps:  
      - *restore_repo
      - checkout
      - *save_repo
      - restore_cache:
          keys: 
            - v0-dependencies36-{{ checksum "requirements.txt"}}
            - v0-dependencies36        
      - run: |
            python3 -m venv ~/venv36
            . ~/venv36/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install .
            cd test
            pytest -v --cov satstac --cov-report term-missing
      - save_cache:
          key: v0-dependencies36-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv36

  deploy:
    <<: *container_python36
    steps:
      - *restore_repo
      - run:
          name: Deploy
          command: |
            . ~/venv/bin/activate
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            pip install twine
            python setup.py sdist
            VERSION=`awk -F\' '{print $2,$4}' satstac/version.py`
            git tag $VERSION
            git push origin $VERSION
            twine upload --username "${PYPI_USER}" --password "${PYPI_PASS}" dist/*


workflows:
  version: 2
  build_test_27:
    jobs:
      - build_and_test_27
  build_test_deploy_36:
    jobs:
      - build_and_test_36
      - deploy:
          requires:
            - build_and_test_36
          filters:
            branches:
              only: master
