# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

# Environment variables required:
# - PYPI_USER / PYPI_PASS: for publishing package to PyPi

version: 2


references:

  container_python36: &container_python36
    docker:
      - image: circleci/python:3.6.2

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v0-repo-{{ .Branch }}-{{ .Revision }}
        - v0-repo-{{ .Branch }}
        - v0-repo
  
  restore_dependencies: &restore_dependencies
    restore_cache:
      keys: 
        - v0-dependencies36-{{ checksum "requirements.txt"}}
        - v0-dependencies36        

jobs:

  checkout_code:
    <<: *container_python36
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project

  install_and_test_36:
    <<: *container_python36
    steps:  
      - *restore_repo
      - *restore_dependencies
      - run: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install .
            cd test
            pytest -v --cov satstac --cov-report term-missing
      - save_cache:
          key: v0-dependencies36-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv

  deploy:
    <<: *container_python36
    steps:
      - *restore_repo
      - *restore_dependencies
      - run:
          name: Deploy
          command: |
            . ~/venv/bin/activate
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            pip install twine
            python setup.py sdist
            VERSION=`awk -F\' '{print $2,$4}' satstac/version.py`
            git tag $VERSION
            git push origin $VERSION
            twine upload --username "${PYPI_USER}" --password "${PYPI_PASS}" dist/*


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - install_and_test_36:
          requires:
            - checkout_code
      - deploy:
          requires:
            - install_and_test_36
          filters:
            branches:
              only: master
